<?php
/**
 * The Retargeting Magento 2 extension implements the required tagging for Retargeting's
 * functions in Magento 2 based web-shops.
 *
 * @category    Retargeting
 * @package     Retargeting_Tracking
 * @author      Retargeting Team <info@retargeting.biz>
 * @copyright   Retargeting (https://retargeting.biz)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

use Retargeting\Tracker\Block\Tracker;

/**
 * @var $block Tracker
 */
$trackingAPIKey = $block->getConfig(\Retargeting\Tracker\Helper\Data::RETARGETING_TRACKING_API_KEY);
$addToCartButtonId = $block->getConfig(\Retargeting\Tracker\Helper\Data::RETARGETING_ADD_TO_CART_BUTTON_ID);
$priceLabelId = $block->getConfig(\Retargeting\Tracker\Helper\Data::RETARGETING_PRICE_LABEL_ID);
$shopCartUrl = $block->getConfig(\Retargeting\Tracker\Helper\Data::RETARGETING_SHOPPING_CART_URL);
?>

<!-- Retargeting Tracking Code <?php echo $this->escapeHtml($block->getRetargetingTrackerVersion()); ?> -->
<!--suppress JSUndeclaredVariable -->
<script>
    (function () {
        ra_key = '<?php echo $block->getPageTrackingCode($trackingAPIKey); ?>';
        ra_params = {
            add_to_cart_button_id: '<?php echo $addToCartButtonId; ?>',
            price_label_id: '<?php echo $priceLabelId; ?>'
        };
        var ra = document.createElement('script');
        ra.type = 'text/javascript';
        ra.async = true;
        ra.src = ('https:' == document.location.protocol ? 'https://' : 'http://') +
            'tracking.retargeting.biz/v3/rajs/' + ra_key + '.js';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(ra, s);
    })();

    <?php
    /**
     * AddToCart
     */
    /** @noinspection PhpUndefinedMethodInspection */
    // echo $block->getCatalogSession()->getAddToCart();
    /** @noinspection PhpUndefinedMethodInspection */
    $block->getCatalogSession()->unsAddToCart();

    /** @var $block Tracker */
    echo $block->getSaveOrderTrackingCode();

    ?>


    var _ra = _ra || {};
    _ra.setCartUrlInfo = {
        'url': '<?php echo $block->getUrl('checkout/cart', ['_secure' => true]); ?>'
    };

    if (_ra.ready !== undefined) {
        _ra.setCartUrl(_ra.setCartUrlInfo.url);
    }
</script>
<!-- Retargeting Tracking Code -->
