<?php
/**
 * The Retargeting Magento 2 extension implements the required tagging for Retargeting's
 * functions in Magento 2 based web-shops.
 *
 * @category    Retargeting
 * @package     Retargeting_Tracking
 * @author      Retargeting Team <info@retargeting.biz>
 * @copyright   Retargeting (https://retargeting.biz)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<script>
    var _ra = _ra || {};
    var sendProductInfo = <?php echo $this->sendProduct(); ?>;
    
    _ra.sendProductInfo = sendProductInfo;

    if (_ra.ready !== undefined) {
        _ra.sendProduct(_ra.sendProductInfo);
    }
    
    window.addEventListener("load", function(){
        document.querySelector(ra_params.add_to_cart_button_id).addEventListener("click", function(){
            if (_ra.ready !== undefined) {
                _ra.addToCart(sendProductInfo.id, document.querySelector("#qty").value, false);
            }
        });
    });
</script>
