<?php
/**
 * The Retargeting Magento 2 extension implements the required tagging for Retargeting's
 * functions in Magento 2 based web-shops.
 *
 * @category    Retargeting
 * @package     Retargeting_Tracking
 * @author      Retargeting Team <info@retargeting.biz>
 * @copyright   Retargeting (https://retargeting.biz)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<script>
    var _ra = _ra || {};
    _ra.sendCategoryInfo = <?php echo $this->getSendCategory(); ?>;

    if (_ra.ready !== undefined) {
        _ra.sendCategory(_ra.sendCategoryInfo);
    }
</script>