<?php
/**
 * The Retargeting Magento 2 extension implements the required tagging for Retargeting's
 * functions in Magento 2 based web-shops.
 *
 * @category    Retargeting
 * @package     Retargeting_Tracking
 * @author      Retargeting Team <info@retargeting.biz>
 * @copyright   Retargeting (https://retargeting.biz)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<script>
    var _ra = _ra || {};
    _ra.sendProductInfo = <?php echo $this->sendProduct(); ?>;
    
    var Product_ID = _ra.sendProductInfo.id;

    if (_ra.ready !== undefined) {
        _ra.sendProduct(_ra.sendProductInfo);
    }
    
    window.addEventListener("load", function(){
        if (Product_ID !== undefined) {
            _ra.addToCartInfo = {
                "product_id": Product_ID,
                "quantity": 1,
                "variation": false
            };
            document.querySelector("#qty").addEventListener("change", function() {
                _ra.addToCartInfo.quantity = this.value;
            });
            document.querySelector(ra_params.add_to_cart_button_id)
                .addEventListener("click", function(){
                _ra.addToCart(_ra.addToCartInfo.product_id, _ra.addToCartInfo.quantity, _ra.addToCartInfo.variation);
            });
        }
    });
</script>
